---
title: "Lab 12"
output: html_document
date: "2022-12-06"
---

```{r}
require(here)
dat_bird = read.csv(here("data", "bird.sub.csv"))
dat_habitat = read.csv(here("data", "hab.sub.csv"))

birdhab = merge(
  dat_bird, 
  dat_habitat,
  by = c("basin", "sub"))
```

##linear
```{r}
linear = function(x, y_int , slope)
{
  return( y_int + (slope * x))
}
```

##linear simulator
```{r}
linear_simulator = function (x, y_int, slope, st_dev)
{
  noise = rnorm(length(x), mean = 0, sd = st_dev)
  return((y_int + (slope * x))+ noise)
}
```

```{r}
fit_1 = lm(BRCR ~ ls, data = birdhab)
fit_1_coefs = coefficients(fit_1)
str(fit_1_coefs)
fit_1_coefs

fit_1_summary = summary(fit_1)
str(fit_1_summary)
fit_1_summary$sigma
```

```{r}
int_obs = fit_1_coefs[1]
slope_obs = fit_1_coefs[2]
sd_obs = fit_1_summary$sigma
```

```{r}
y_sim = linear_simulator(
  x = birdhab$ls,
  y_int = int_obs,
  slope = slope_obs,
  st_dev = sd_obs
)

fit_sim = lm(y_sim ~ birdhab$ls)
summary(fit_sim)
```
```{r}
sum_1 = summary(fit_sim)
sum_1$coefficients
sum_1$coefficients[2,4]
```

```{r}
linear_sim_fit = function(x, slope, y_int, st_dev)
{
  y_sim = linear_simulator(
    x = x,
    y_int = y_int,
    slope = slope,
    st_dev = st_dev
  )
  fit_sim = lm(y_sim ~ x)
  return(fit_sim)
}
```

##sim_sample_size
```{r}
alpha = 0.05
n_sims = 30
p_vals = numeric(n_sims)

sample_sizes = seq(2, 20)
sample_size_powers = numeric(length(sample_sizes))

# The maximum x value in the simulation.
# Use the maximum observed x-value in the data
max_x = max(birdhab$ls)

for(j in 1:length(sample_sizes))
{
  # A sequence of equally-spaced x-values:
  x_vals = seq(0, max_x, length.out = sample_sizes[j])
  
  for(i in 1:n_sims)
  {
    fit_sim = linear_sim_fit(
      x = x_vals,
      y_int = int_obs,
      slope = slope_obs,
      st_dev = sd_obs
    )
    p_vals[i] = summary(fit_sim)$coefficients[2, 'Pr(>|t|)']
  }
  sample_size_powers[j] = sum(p_vals < alpha) / n_sims
}


sim_sample_size = 
  data.frame(
    sample_size = sample_sizes,
    power       = sample_size_powers)
```


```{r}
fit_lowess_30 = loess(power ~ sample_size, data = sim_sample_size, span = 0.3)
```

```{r}
newdata_sample_size = data.frame(sample_size = seq(2, 20, length.out = 100)) 
```

```{r}
{plot(
  x = newdata_sample_size$sample_size,
  y = predict(fit_lowess_30, newdata = newdata_sample_size),
  type = "l",
  ylab = "Statistical Power", xlab = "Sample Size", main = "Sample Size/Power Simulation \n LOWESS: 30%")
lines(power ~ sample_size, type = "p", col = "red", pch = 19, data = sim_sample_size)
legend(
  'bottomright',
  legend=c('Smoothed','Original'),
  lty = c(1, 0), pch = c(NA_integer_, 19), col=c(1,2))
}
```

```{r}
ricker_fun = function(x, a, b) 
{
  return(a * x * exp(-b * x))
}

exp_fun = function(x, a , b)
{
  return(a * exp(-b * x))
}
```

```{r}
require(here)
dat_dispersal = read.csv(here("data", "dispersal.csv"))
```

```{r}
fit_ricker_nls = nls(
  disp.rate.ftb ~ ricker_fun(dist.class, a, b),
  data = dat_dispersal,
  start = list(b = 0, a = 1))
summary(fit_ricker_nls)
```

```{r}
plot(disp.rate.ftb ~ dist.class, data = dat_dispersal)
```

```{r}
dist_newdata = data.frame(dist.class = seq(0, 1600, length.out = 1600))  
```


```{r}
plot(disp.rate.ftb ~ dist.class, data = dat_dispersal, xlim = c(0, 1600),
     main = "Salamander NLS Plot", xlab = "Distance Class", ylab = "Dispersal Rate")
lines(predict(fit_ricker_nls, newdata = dist_newdata))
curve(ricker_fun(x, 0.007, 0.004), add = TRUE, col = "red", lty = 2)
legend("topright", legend = c("NLS fit", "guess"), lty = c(1, 2), col = c(1, 2))
```

```{r}
dat_bird = read.csv(here("data", "bird.sta.csv"))
dat_habitat = read.csv(here("data", "hab.sta.csv"))
dat_all = merge(dat_bird, dat_habitat)
dat_all$HEWA_pres = dat_all$HEWA > 0
dat_all$GCKI_Pres = dat_all$GCKI > 0
```

```{r}
# Hermit warbler presence/absence
dat_all$HEWA_pres = dat_all$HEWA > 0

# Create model fits
fit_hewa_slope = glm(HEWA_pres ~ slope, data = dat_all, family = binomial)
fit_hewa_ba_tot = glm(HEWA_pres ~ ba.tot, data = dat_all, family = binomial)
fit_hewa_both_additive = glm(HEWA_pres ~ slope + ba.tot, data = dat_all, family = binomial)
fit_hewa_both_interactive = glm(HEWA_pres ~ slope * ba.tot, data = dat_all, family = binomial)
```

```{r}
summary(fit_hewa_both_additive)
```

```{r}
n = 500

slope_newdata = data.frame(
  slope = seq(
    from = min(dat_all$slope, na.rm = T),
    to = max(dat_all$slope, na.rm = T),
    length.out = n
  )
)
```

```{r}
n = 500

ba_newdata = data.frame(
  ba.tot = seq(
    from = min(dat_all$ba.tot, na.rm = T),
    to = max(dat_all$ba.tot, na.rm = T),
    length.out = n
  )
)
```


```{r}
slope_newdata$hewa_predicted = 
  predict(
    fit_hewa_slope,
    newdata = slope_newdata,
    type = "response"
  )

ba_newdata$hewa_predicted = 
  predict(
    fit_hewa_ba_tot,
    newdata = ba_newdata,
    type = "response"
  )
```

```{r}
par(mfrow = c(2, 1))

# Presence/absence data, translucent points:
plot(
  HEWA_pres ~ slope, data = dat_all,
  xlab = "Percent Slope",
  ylab = "HEWA presence/absence",
  pch = 16, cex = 1.5, col = gray(0, 0.2)
)

lines(hewa_predicted ~ slope, data = slope_newdata)

plot(
  HEWA_pres ~ ba.tot, data = dat_all,
  xlab = "Basal Area",
  ylab = "HEWA presence/absence",
  pch = 16, cex = 1.5, col = gray(0, 0.2)
)

lines(hewa_predicted ~ ba.tot, data = ba_newdata)
```

##AIC
```{r}
AIC(
  fit_hewa_ba_tot,
  fit_hewa_slope,
  fit_hewa_both_additive,
  fit_hewa_both_interactive)
```

```{r}
# Hermit warbler presence/absence
dat_all$GCKI_pres = dat_all$GCKI > 0

# Create model fits
fit_gcki_slope = glm(GCKI_pres ~ slope, data = dat_all, family = binomial)
fit_gcki_ba_tot = glm(GCKI_pres ~ ba.tot, data = dat_all, family = binomial)
fit_gcki_both_additive = glm(GCKI_pres ~ slope + ba.tot, data = dat_all, family = binomial)
fit_gcki_both_interactive = glm(GCKI_pres ~ slope * ba.tot, data = dat_all, family = binomial)
```

```{r}
slope_newdata$gcki_predicted = 
  predict(
    fit_gcki_slope,
    newdata = slope_newdata,
    type = "response"
  )

ba_newdata$gcki_predicted = 
  predict(
    fit_gcki_ba_tot,
    newdata = ba_newdata,
    type = "response"
  )
```

```{r}
par(mfrow = c(2, 1))

# Presence/absence data, translucent points:
plot(
  GCKI_pres ~ slope, data = dat_all,
  xlab = "Percent Slope",
  ylab = "GCKI presence/absence",
  pch = 16, cex = 1.5, col = gray(0, 0.2)
)

lines(gcki_predicted ~ slope, data = slope_newdata)

plot(
  GCKI_pres ~ ba.tot, data = dat_all,
  xlab = "Basal Area",
  ylab = "GCKI presence/absence",
  pch = 16, cex = 1.5, col = gray(0, 0.2)
)

lines(gcki_predicted ~ ba.tot, data = ba_newdata)
```

```{r}
AIC(
  fit_gcki_ba_tot,
  fit_gcki_slope,
  fit_gcki_both_additive,
  fit_gcki_both_interactive)
```
```{r}
summary(fit_gcki_both_interactive)
```

```{r}
n = 50

ba.tot = seq(
  from = min(dat_all$ba.tot, na.rm = T),
  to = max(dat_all$ba.tot, na.rm = T),
  length.out = n)
slope = seq(
  from = min(dat_all$slope, na.rm = T),
  to = max(dat_all$slope, na.rm = T),
  length.out = n)
```

```{r}
new_dat_all = expand.grid(
  ba.tot = ba.tot,
  slope = slope)
head(new_dat_all)
```
```{r}
tail(new_dat_all)
```
```{r}
new_dat_all$pred_add = predict(
  fit_gcki_both_additive,
  newdata = new_dat_all,
  type = "response")
new_dat_all$pred_int = predict(
  fit_gcki_both_interactive,
  newdata = new_dat_all,
  type = "response")
```

```{r}

z_gcki_add = matrix(
  new_dat_all$pred_add,
  nrow = length(ba.tot),
  byrow = FALSE)

z_gcki_int = matrix(
  new_dat_all$pred_int,
  nrow = length(ba.tot),
  byrow = FALSE)
```

```{r}
require(rgl)

rgl::persp3d(
  x = ba.tot,
  y = slope,
  z = z_gcki_add,
  col = "steelblue",
  xlab = "Basal Area",
  ylab = "Slope",
  zlab = "Pr(present)",
  alpha = 0.4)
rglwidget()
```

```{r}
par(mfrow = c(1, 2))
contour(
  x = ba.tot, y = slope,
  z = z_gcki_add,
  xlab = "Total Basal Area",
  ylab = "Percent Slope",
  main = "Additive")
contour(
  x = ba.tot,
  y = slope,
  z = z_gcki_int,
  xlab = "Total Basal Area",
  ylab = "Percent Slope",
  main = "Interactive")
```

##fancy contour plot
```{r}
# Create a color ramp function using heat colors
colorfunc = colorRampPalette(
  heat.colors(length(ba.tot)))

# Figure out the indices of the color ramp
col_indices_gcki_add = findInterval(
  new_dat_all$pred_add,
  seq(
    min(new_dat_all$pred_add),
    max(new_dat_all$pred_add),
    length.out = 50))

rgl::persp3d(
  x = ba.tot,
  y = slope,
  z = z_gcki_add,
  xlab = "Basal Area",
  ylab = "Slope",
  zlab = "Pr(present)",
  alpha = 0.9,
  col = colorfunc(50)[col_indices_gcki_add]
)
rglwidget()
```

##fancy terrain plot
```{r}
png(
  filename = here("lab_12_terrain_plot.png"),
  width = 1600, height = 1500,
  res=180
)
par(mfrow = c(2, 1))


# Presence/absence data, translucent points:
{plot(
  GCKI_pres ~ slope, data = dat_all, axes = FALSE,
  xlab = "Percent Slope",
  ylab = "",
  ylim = c(-0.2, 1.2),
  pch = 16, cex = 1.5, col = hcl.colors(1, palette = "BluYl", alpha = 0.1)
)
axis(1, at = seq(0, 110, by = 10))
axis(2, at = c(0, 1), labels = c("Absent", "Present"), las = 2)
box()
lines(gcki_predicted ~ slope, data = slope_newdata)}
{
plot(
  GCKI_pres ~ ba.tot, data = dat_all, axes = FALSE,
  xlab = "Basal Area",
  ylab = "",
  ylim = c(-0.2, 1.2),
  pch = 16, cex = 1.5, col = hcl.colors(1, palette = "BluYl", alpha = 0.1)
)
axis(1, at = seq(0, 110, by = 10))
axis(2, at = c(0, 1), labels = c("Absent", "Present"), las = 2)
box()

lines(gcki_predicted ~ ba.tot, data = ba_newdata)
}
```