install.packages("palmerpenguins")
install.packges(here)
install.packages("here")
require(palmerpenguins)
require(here)
library("palmerpenguins")
penguins = data.frame(penguins)
summmary(penguins)
summary(penguins)
boxplot(flipper_length_mm~sex, data=penguins)
par(mfrow = c(1,2))
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm~sex, data=penguins)
require(here)
png(filename =here("penguin bill depth.png"),width=800,height=600)
par(mfrow =c(1,2))
boxplot(flipper_length_mm~sex, data=penguins)
boxplot(bill_depth_mm~sex, data=penguins)
dev.off()