---
title: "Lab_08"
output: html_document
date: "2022-11-02"
---

```{r}
require(here)
veg = read.csv(here("data", "vegdata.csv"))
require(palmerpenguins)

require(simpleboot)
require(boot)
```

##removing gentoo 
```{r}
boxplot(
  flipper_length_mm ~ species, data = penguins,
  ylab = "Flipper length (mm)")

dat_pen = subset(penguins, species != "Chinstrap")
boxplot(
  flipper_length_mm ~ species, data = dat_pen,
  ylab = "Flipper length (mm)")

dat_pen = droplevels(subset(penguins, species != "Gentoo"))
{
  par(mfrow = c(1, 2))
  boxplot(
    flipper_length_mm ~ species, data = dat_pen,
    ylab = "Flipper length (mm)",
    main = "Gentoo Penguins Removed")
}
```

##T-test on flipper length, Adelie have shorter than Chinstrap
##One-tailed t-test
```{r}
t.test(flipper_length_mm ~ species, data = dat_pen, alternative = "less")

```
##two sample bootstrapping
##Creating the two new sample sets
```{r}
adelie_flip = na.omit(subset(penguins, species == "Adelie")$flipper_length_mm)
chinstrap_flip = na.omit(subset(penguins, species == "Chinstrap")$flipper_length_mm)

pen_boot = two.boot(adelie_flip, chinstrap_flip, FUN = mean, R = 10000)
pen_boot$t
str(pen_boot)

pen_sd = sd(pen_boot$t)
pen_sd

hist(pen_boot$t,
     main = "Bootstrapped Difference of Means",
     xlab = "(Adelie - Chinstrap) Flipper Lengths"
     )

quantile(
  pen_boot$t,
  c(0.025, 0.975))

median(pen_boot$t)
mean(pen_boot$t)
```

##ecdf FUNCTION
```{r}
pen_ecdf = ecdf(pen_boot$t)
plot(pen_ecdf)
pen_ecdf(-8)

```

##Tree data
```{r}

boxplot(pine ~ treatment, dat = veg)
```

```{r}
dat_tree = droplevels(subset(veg, treatment %in% c("control", "clipped")))
boxplot(pine ~ treatment, dat = dat_tree)
```

```{r}
table(dat_tree$treatment)
dat_tree_clipped = na.omit(subset(dat_tree, treatment == "clipped")$pine)
dat_tree_control = na.omit(subset(dat_tree, treatment == "control")$pine)

wilcox.test(pine ~ treatment, data = dat_tree)
```
##Bootstrapping tree data
```{r}
tree_boot = two.boot(dat_tree_clipped, dat_tree_control, FUN = mean, R = 1000)
tree_boot$t
str(tree_boot)
quantile(tree_boot$t,
  c(0.025, 0.975))
```

```{r}
mean(dat_tree_clipped) - mean(dat_tree_control)
```

##Bird time
```{r}
dat_hab = read.csv(here("data", "hab.sub.csv"))
dat_bird = read.csv(here("data", "bird.sub.csv"))
dat_all = merge(
  dat_bird, 
  dat_hab,
  by = c("basin", "sub"))

head(dat_all[, c("b.sidi", "s.sidi")])
```
##Z-standardization
```{r}
# Calculate the sample mean and sd:
b_sidi_mean = mean(dat_all$b.sidi, na.rm = TRUE)
b_sidi_sd   = sd(dat_all$b.sidi, na.rm = TRUE)

# Use the subset-by-name symbol ($) to create a 
# new column of z-standardized values.

dat_all$b.sidi.standardized = (dat_all$b.sidi - b_sidi_mean)/b_sidi_sd
mean(dat_all$b.sidi.standardized)
sd(dat_all$b.sidi.standardized)


s_sidi_mean = mean(dat_all$s.sidi, na.rm = TRUE)
s_sidi_sd   = sd(dat_all$s.sidi, na.rm = TRUE)

dat_all$s.sidi.standardized = (dat_all$s.sidi - s_sidi_mean)/s_sidi_sd
mean(dat_all$s.sidi.standardized)
sd(dat_all$s.sidi.standardized)


```
##plotting data
```{r}
plot(
  b.sidi ~ s.sidi, data = dat_all,
  main = "Simpson's diversity indices",
  xlab = "Vegetation cover diversity",
  ylab = "Bird diversity")

fit_1 = lm(b.sidi ~ s.sidi, data = dat_all)
coef(fit_1)
slope_observed = coef(fit_1)[2]

{plot(
  b.sidi ~ s.sidi, data = dat_all,
  main = "Simpson's diversity indices",
  xlab = "Vegetation cover diversity",
  ylab = "Bird diversity")
abline(fit_1)}

dat_1 = 
  subset(
    dat_all,
    select = c(b.sidi, s.sidi))
```



##Monte Carlo Simulation
```{r}
set.seed(123)
index_1 = sample(nrow(dat_1), replace = TRUE)
index_2 = sample(nrow(dat_1), replace = TRUE)

dat_resampled_i = 
  data.frame(
    b.sidi = dat_1$b.sidi[index_1],
    s.sidi = dat_1$s.sidi[index_2]
  )

fit_resampled_i = lm(b.sidi ~ s.sidi, data = dat_resampled_i)
slope_resampled_i = coef(fit_resampled_i)[2]

print(slope_resampled_i)
```

```{r}
plot(
  b.sidi ~ s.sidi, data = dat_resampled_i,
  main = "Simpson's diversity indices (MC resampled data)",
  xlab = "Vegetation cover diversity",
  ylab = "Bird diversity")
abline(fit_resampled_i)
```

##our monte carlo simulation
```{r}
m = 10000 
result_mc = numeric(m) 

for(i in 1:m)
{
  index_1 = sample(nrow(dat_1), replace = TRUE)
  index_2 = sample(nrow(dat_1), replace = TRUE)

  dat_resampled_i = 
   data.frame(
     b.sidi = dat_1$b.sidi[index_1],
     s.sidi = dat_1$s.sidi[index_2]
   )

  fit_resampled_i = lm(b.sidi ~ s.sidi, data = dat_resampled_i)
  result_mc[i] = coef(fit_resampled_i)[2]
} 
plot(
  b.sidi ~ s.sidi, data = dat_resampled_i,
  main = "Simpson's diversity indices (MC resampled data)",
  xlab = "Vegetation cover diversity",
  ylab = "Bird diversity")
abline(fit_resampled_i)

```

##MC histogram
```{r}
hist(result_mc, main = "Monte Carlo resampled slopes", xlab = "Monte Carlo results")
abline( v = slope_observed, lty = 1, col = "blue", lwd = 2)
crit_slope = quantile(result_mc, 0.05)
crit_slope

abline( v= crit_slope, lty = 2, col = "red", lwd = 2)

```


##Bootstrapping
```{r}
set.seed(345)
index_1 = sample(nrow(dat_1), replace = TRUE)

dat_boot = dat_1[index_1, ]
head(dat_boot)
```
```{r}
fit_bs1 = lm(b.sidi ~ s.sidi, data = dat_boot)

coef(fit_bs1)
```

```{r}
m = 10000 
result_boot = numeric(m) 

for(i in 1:m)
{
  index_1 = sample(nrow(dat_1), replace = TRUE)

  dat_boot = dat_1[index_1, ]

  fit_bs1 = lm(b.sidi ~ s.sidi, data = dat_boot)
  result_boot[i] = coef(fit_bs1)[2]
} 
hist(
  result_boot,
  main = "Ian's Alternative Distribution of Regression Slope",
  xlab = "Slope Parameter")
abline(v = slope_observed, lty = 2, col = "red", lwd = 2)
abline(v = 0, lty = 2, col = 1, lwd = 2)
```

```{r}

plot(
  density(result_mc),
  main = "Ian's Null and Alternative Distribution Density Plot",
  xlab = "Slope Coefficient", lty = 2
  )
lines(
  density(result_boot), col = "red"
)
legend(
  "topright",
  legend = c('Null', 'Alternative'),
  col = c (2, 4), lty = c(1, 2)
)
```


