---
title: "Likelihood"
output: html_document
date: "2022-10-25"
---
##Walkthrough
```{r}
x_observed = c(2, 6)
print(x_observed)

dpois(x = 2, lambda = 4.5) 
dpois(x = 6, lambda = 4.5)
dpois(x = 2, lambda = 4.5) * dpois(x = 6, lambda = 4.5)

wiwa_counts = c(2, 6)
dpois(x = wiwa_counts, lambda = 4.5)
prod(dpois(x = wiwa_counts, lambda = 4.5))
sum(log(dpois(x = wiwa_counts, lambda = 4)))

```
##Bird Data
```{r}
dat_bird = read.csv(here::here("data", "bird.sta.csv"))
dat_habitat = read.csv(here::here("data", "hab.sta.csv"))
dat_all = merge(dat_bird, dat_habitat)
```

```{r}
summary(dat_all$WIWA)
hist(dat_all$WIWA)
hist(dat_all$WIWA, breaks = 7)

```
##Histogram with correct number of bars
```{r}
hist(dat_all$WIWA, breaks = 0:7 - 0.5)

```
##Same idea but with an unknown amount of max data points
```{r}
par(mfrow = c(1, 2))
dat = dat_all$WIWA
hist(dat, breaks = 0:(max(dat) + 1) - 0.5, main = "Histogram of\nWilson's Warbler counts")

dat = dat_all$GRJA
hist(dat, breaks = 0:(max(dat) + 1) - 0.5, main = "Histogram of\nGray Jay counts")
```
##Histogram of WIWR
```{r}
hist(dat_all$WIWR, breaks = 0:7 - 0.5, main = "Histogram of Winter Wren Data")

```
##GUess and checking for max lambda value
```{r}
sum(log(dpois(x = dat_all$WIWR, lambda = 1.5)))
```
##using the binomial data
```{r}
WIWR_count = sum(table(dat_all$WIWR))
WIWR_count
mean(dat_all$WIWR)
max(dat_all$WIWR)
```
##making a binomial distribution

```{r}

sum(log(dbinom(dat_all$WIWR, 7, 0.24)))

```

##Question 12-14
```{r}
set.seed(1)
vec_rnorm = rnorm(n = 10, mean = 0, sd = 1)
sum(log(dnorm(vec_rnorm, mean =0.15, sd = 0.75)))

```
```{r}
sum(log(dnorm(vec_rnorm, mean = 0.2, sd = 0.75)))
```
##Question 15-16
```{r}
require(palmerpenguins)
flip_length = na.omit(penguins$flipper_length_mm)

flip_mean = mean(flip_length)
flip_sd = sd(flip_length)

dnorm(flip_length, mean = flip_mean, sd = flip_sd)

sum(log(dnorm(flip_length, flip_mean, flip_sd)))

```
```{r}
flip_mean
flip_sd
```

