---
title: "Lab_05"
output: html_document
date: "2022-10-12"
---
##Creating the Ricker Function
```{r}
ricker_fun = function(x, a, b) 
{
  return(a * x * exp(-b * x))
}
```
```{r}
?curve
curve(
  ricker_fun(x, 1, 1), 
  from = 0, to = 5, add = FALSE, 
  main = "Ricker function: a = 1, b = 1",
  ylab = "f(x)", xlab = "x")
```
```{r}
exp_fun = function(x, a , b)
{
  return(a * exp(-b * x))
}
```

```{r}
curve(
  exp_fun(x, 2.2, 1/15), add = FALSE, from = 0, to = 50,
  ann = FALSE, axes = TRUE, ylab = "f(x)"); box()
```
```{r}
# Seed the RNG so we can reproduce our results
set.seed(1234567)

# Specify the x-range and number of points:
n_pts = 50
x_min = 2
x_max = 10

# Generate the x-values
x_sim = runif(n_pts, min = x_min, max = x_max)

param_intercept = 2.3
param_slope = 0.67
y_pred = param_intercept + x_sim * param_slope
plot(x_sim, y_pred, main = "Simulated Data\nNo Errors", xlab = "", ylab = "")
```
```{r}
error_mean = 0
error_sd = 0.25

y_observed = 
  y_pred + 
  rnorm(
    n = n_pts, 
    mean = error_mean, 
    sd = error_sd)
plot(x_sim, y_observed, main = "Normally Distributed Errors\n Constant Variance", xlab = "", ylab = "")
```
```{r}
error_mean = 0
error_sd = 0.1

y_observed_2 = 
  y_pred + 
  rnorm(
    n = n_pts, 
    mean = error_mean, 
    sd = error_sd * x_sim)

par(mfrow = c(1, 2))
plot(x_sim, y_observed, main = "Normally Distributed Errors\n Constant Variance", xlab = "", ylab = "")
plot(x_sim, y_observed_2, main = "Normally Distributed Errors\n Increasing Variance", xlab = "", ylab = "")
```
```{r}
error_mean = 0
error_sd = 0.1

error_sd_3 = error_sd * rexp(1.2, rate = 1)

y_observed_3 = 
  y_pred + 
  rnorm(
    n = n_pts,
    mean = error_mean,
    sd = error_sd_3)

plot(x_sim, y_observed_3, main = "Normally Distributed Errors\n Exponential Variance", xlab = "", ylab = "")

dev.off()
```

```{r}
fit_1 = lm(y_observed ~ x_sim)
fit_2 = lm(y_observed_2 ~ x_sim)
fit_3 = lm(y_observed_3 ~ x_sim)

par(mfrow = c(1, 3))

plot(y_observed ~ x_sim); abline(fit_1)
plot(y_observed_2 ~ x_sim); abline(fit_2)
plot(y_observed_3 ~ x_sim); abline(fit_3)
```
##Calling data frame
```{r}
require(here)
dat_dispersal = read.csv(here("data", "dispersal.csv"))
```
##Plotting multiple curves in the same graph
```{r}


exp_fun = function(x, a , b)
{
  return(a * exp(-b * x))
}

{
curve(
  exp_fun(x, 2.2, 1/15), add = FALSE, from = 0, to = 50, ylim = c(-0.1,2),
  ann = FALSE, axes = TRUE, ylab = "f(x)", col = "black"); box()
curve(
  exp_fun(x, 1.9, 0.1), add = TRUE, col = "black")
curve(
  exp_fun(x, 1.9, 0.3), add = TRUE, col = "black", lty = 2)
curve(
  exp_fun(x, 1.2, 0.2), add = TRUE, col = "red")
curve(
  exp_fun(x, 1.2, 0.4), add = TRUE, col = "red", lty = 2)
}

```

##Ricker function time
```{r}
ricker_fun = function(x, a, b) 
{
  return(a * x * exp(-b * x))
}
{
curve(
  ricker_fun(x, 25, 0.2), 
  from = 0, to = 50, ylim = c(0,100), add = FALSE, 
  main = "Ricker function",
  ann = FALSE,
  col = "black")
curve(
  ricker_fun(x, 20, 0.2), 
  add = TRUE, col = "black", lty = 2)
curve(
  ricker_fun(x, 10, 0.2), 
  add = TRUE, col = "black", lty = 2)
curve(
  ricker_fun(x, 75, 0.3), 
  add = TRUE, col = "red")
curve(
  ricker_fun(x, 50, 0.3), 
  add = TRUE, col = "red", lty = 2)
curve(
  ricker_fun(x, 40, 0.3), 
  add = TRUE, col = "red", lty = 2)
}

```
```{r}
  line_point_slope = function(x, x1, y1, slope)
  {
    get_y_intercept = 
      function(x1, y1, slope) 
        return(-(x1 * slope) + y1)
    
    linear = 
      function(x, yint, slope) 
        return(yint + x * slope)
    
    return(linear(x, get_y_intercept(x1, y1, slope), slope))
  }
```

##Linear function
```{r}
{
plot(
    dat_dispersal$dist.class,
    dat_dispersal$disp.rate.ftb,
    xlim = c(0, 1500),
    xlab = "distance class", 
    ylab = "standardized dispersal rate", 
    main = "Marbled Salamander - first time breeders\n(Bad) linear model")
  curve(line_point_slope(x, 1500, 0.8, -0.00001), add = TRUE)
  curve(line_point_slope(x, 1500, 0.1, -0.0003), add = TRUE)
  curve(line_point_slope(x, 1500, 0.01, -0.0002), add = TRUE, col = "red")
}
```
##Exponential Function
```{r}
{
plot(
    dat_dispersal$dist.class,
    dat_dispersal$disp.rate.ftb,
    xlim = c(0, 1500),
    xlab = "distance class", 
    ylab = "standardized dispersal rate", 
    main = "Marbled Salamander - first time breeders\n Exponential model")
  curve(exp_fun(x, 0.8, 0.0025), add = TRUE, col = "black")
}
```
##Ricker model fit
```{r}
{
plot(
    dat_dispersal$dist.class,
    dat_dispersal$disp.rate.ftb,
    xlim = c(0, 1500),
    xlab = "distance class", 
    ylab = "standardized dispersal rate", 
    main = "Marbled Salamander - first time breeders\n Ricker model")
curve(ricker_fun(x, 0.007, 0.004), 
  add = TRUE, col = "red", lty = 2)
}
```
##Creating residuals
```{r}
par(mfrow = c(1,3))

y_pred_linear = line_point_slope(dat_dispersal$dist.class, 1500, 0.01, -0.0002)
dat_dispersal$y_pred_linear = y_pred_linear
resids_linear = dat_dispersal$y_pred_linear - dat_dispersal$disp.rate.ftb
dat_dispersal$resids_linear = resids_linear
hist(dat_dispersal$resids_linear, main = "Histogram for Linear Residuals")


y_pred_exp = exp_fun(dat_dispersal$dist.class, 0.8, 0.0025)
dat_dispersal$y_pred_exp = y_pred_exp
resids_exp = dat_dispersal$y_pred_exp - dat_dispersal$disp.rate.ftb
dat_dispersal$resids_exp = resids_exp
hist(dat_dispersal$resids_exp, main = "Histogram for Exponential Residuals")


y_pred_ricker = ricker_fun(dat_dispersal$dist.class, 0.007, 0.004)
dat_dispersal$y_pred_ricker = y_pred_ricker
resids_ricker = dat_dispersal$y_pred_ricker - dat_dispersal$disp.rate.ftb
dat_dispersal$resids_ricker = resids_ricker
hist(dat_dispersal$resids_ricker, main = "Histogram for Ricker Residuals")

```

