---
title: "Data Exploration and Deterministic Functions"
output: html_document
date: "2022-10-09"
---
##Creating Dat_All Data.Frame which merges bird and habitat data.
```{r}
require(here)
dat_bird = read.csv(
  here("data","bird.sta.csv")
)
head(dat_bird)
dat_habitat = read.csv(
  here("data","hab.sta.csv")
)
head(dat_habitat)

dat_all = merge(dat_bird, dat_habitat)
head(dat_all)
```
##Plotting histograms for elevation, slope, and aspect.
```{r}
png(
  filename = here("Question_1_hist.png"),
  width = 1600, height = 700,
  res=180)
par(mfrow = c(1,3))
hist(dat_all$slope,
     main = "Histogram of sampling site slope", xlab = "slope"
     )
hist(dat_all$aspect,
     main= "Histogram of sampling site aspect", xlab = "aspect")
hist(dat_all$elev,
     main= "Histogram of sampling site elevation", xlab = "elevation")
dev.off()
```

```{r}
png(
  filename = here("Question_7_Scatter.png"),
  width = 1000, height = 2000,
  res=180)
line_point_slope = function(x, x1, y1, slope)
{
  get_y_intercept =
    function(x1, y1, slope)
      return(-(x1 * slope) + y1)
  linear = 
    function(x, yint, slope)
      return(yint + x * slope)
  
  return(linear(x, get_y_intercept(x1, y1, slope), slope))
}
par(mfrow=c(3,1))
plot(x = dat_all$elev, y = dat_all$ba.tot,
     main= "Scatterplot of Total Basal Area and Elevation",
     ylab= "Total Basal Area",
     xlab= "Elevation",
     cex = 0.7)
curve(line_point_slope(x, x1 = 0, y1= 40, slope = -0.04), add = TRUE, col = "red")
plot(y = dat_all$ba.tot, x = dat_all$slope,
     main= "Scatterplot of Total Basal Area and Slope",
     ylab= "Total Basal Area",
     xlab= "Slope",
     cex = 0.7)
curve(line_point_slope(x, x1 = 0, y1= 10, slope = 0.04), add = TRUE, col = "violet")
plot(y = dat_all$ba.tot, x = dat_all$aspect,
     main= "Scatterplot of Total Basal Area and Aspect",
     ylab= "Total Basal Area",
     xlab= "Aspect",
     cex = 0.7)
curve(line_point_slope(x, x1 = 0, y1= 20, slope = 0.01), add = TRUE, col = "orange")
dev.off()
```


