---
title: "lab_07_questions"
output: html_document
date: "2022-10-26"
---

##requiring packages
```{r}
require(here)
require(palmerpenguins)
```
##Creating the data.frame for Gentoo only
```{r}
dat_pen = subset(penguins, species == "Gentoo")
```


##Question 1-5 constructing CI for penguins
```{r}
# Choose significance level
alpha = 0.05

# 2: Calculate sample standard error:
n = sum(!is.na(dat_pen$bill_length_mm))
n
dat_sd = sd(dat_pen$bill_length_mm, na.rm = TRUE)
dat_sd
sse = dat_sd / sqrt(n)
sse
# 3: Calculate critical t-values:
t_crit = abs(qt(alpha / 2, df = n - 1))
t_crit

# 4: Calculate the CI radius:
ci_radius = sse * t_crit


# The CI is the sample mean +/- the radius:
gentoo_bill_length_ci = c(
  lower = mean(!is.na(dat_pen$bill_length_mm)) - ci_radius,
  upper = mean(!is.na(dat_pen$bill_length_mm)) + ci_radius)

print(round(gentoo_bill_length_ci, 4))
```

##Bootstrapping time
```{r}
require(boot)
boot_mean = function(x, i)
{
  return(mean(x[i], na.rm = TRUE))
}
myboot = 
  boot(
    data = dat_pen$bill_length_mm,
    statistic = boot_mean,
    R = 10000)
print(myboot)
str(myboot)
mean(dat_pen$bill_length_mm)
myboot$t0
mean(myboot$t) - myboot$t0
sd(myboot$t)
quantile(
  myboot$t,
  c(0.025, 0.975))
```

##QUestion 9-13
```{r}
rm(list = ls())

# Re-read my data:
moths = read.csv(here("data", "moths.csv"))
moth_dat = moths[,-1]

rarefaction_sampler = function(input_dat, n_iterations)
{
  n_input_rows = nrow(input_dat)

  results_out = matrix(
    nrow = n_iterations,
    ncol = n_input_rows)

  # The outer loop: runs once for each bootstrap iteration.  index variable is i
  for(i in 1:n_iterations)
  {
    # The inner loop: simulates increasing sampling intensity
    # Sampling intensity ranges from 1 site to the complete count of
    # sites in the input data (n)
    for(j in 1:n_input_rows)
    {
      # sample the input data row indices, with replacement
      rows_j = sample(n_input_rows, size = j, replace=TRUE)

      # Creates a new data matrix
      t1 = input_dat[rows_j, ]

      # Calculates the column sums
      t2 = apply(t1, 2, sum)

      # Counts the number of columns in which any moths were observed
      results_out[i, j] = sum(t2 > 0)
    }
  }
  return(results_out)
}

rarefact = rarefaction_sampler(moth_dat, 100)
rarefact
```
##Testing rarefaction function
```{r}
# This clears the current R session's environment
rm(list = ls())

# Re-read my data:
moths = read.csv(here("data", "moths.csv"))

rarefaction_sampler = function(input_dat, n_iterations)
{
  n_input_rows = nrow(input_dat)

  results_out = matrix(
    nrow = n_iterations,
    ncol = n_input_rows)

  # The outer loop: runs once for each bootstrap iteration.  index variable is i
  for(i in 1:n_iterations)
  {
    # The inner loop: simulates increasing sampling intensity
    # Sampling intensity ranges from 1 site to the complete count of
    # sites in the input data (n)
    for(j in 1:n_input_rows)
    {
      # sample the input data row indices, with replacement
      rows_j = sample(n_input_rows, size = j, replace=TRUE)

      # Creates a new data matrix
      t1 = input_dat[rows_j, ]

      # Calculates the column sums
      t2 = apply(t1, 2, sum)

      # Counts the number of columns in which any moths were observed
      results_out[i, j] = sum(t2 > 0)
    }
  }
  return(results_out)
}

rarefact = rarefaction_sampler(moths[,-1], 100)
head(rarefact)
```
##Simulation time
```{r}
moths = read.csv(here("data", "moths.csv"))
rarefact = rarefaction_sampler(moths[,-1], 10000)

```

```{r}
rare_mean = apply(rarefact, 2, mean)
rare_quant = apply(rarefact, 2, quantile, probs=c(0.025, 0.975))
rare = t(rbind(rare_mean, rare_quant))

matplot(
  rare,
  type='l',
  xlab='Number of sampling plots',
  ylab='Species richness',
  main="Ian's Attempt at Rarefaction Curve",
  col = c(3,4,2), lwd = 2
  )

legend(
  'bottomright',
  legend=c('mean','2.5%','97.5%'),
  lty=c(1,2,3),col=c(3,4,2), inset=c(.1,.1))
```

