---
title: "Lab_09"
output: html_document
date: "2022-11-09"
---

```{r}
require(here)
catrate = read.csv(here("data", "catrate.csv"))
head(catrate)
```

```{r}
n_success = sum(catrate$success)
n_years = sum(catrate$years)
binom.test(
  x = n_success,
  n = n_years,
  p = 0.5)
```

```{r}
late_fill_rate = 2/7
normal_fill_rate = 1 - late_fill_rate 
binom.test(
  x = n_success,
  n = n_years,
  p = normal_fill_rate,
  alternative = "less") 
```

```{r}
require(here)
veg = read.csv(here("data", "vegdata.csv"))
head(veg)
boxplot(pine ~ treatment, data = veg)
```

```{r}
veg2 = droplevels(
  subset(
    veg,
    treatment %in% c('control','clipped')
  ))
veg2
# verify that treatment is factorized
veg2$treatment = factor(veg2$treatment)
var.test(
  pine ~ treatment,
  data = veg2)
```

```{r}
shapiro.test(veg2$pine[veg2$treatment=="control"])
shapiro.test(veg2$pine[veg2$treatment=="clipped"])
```

```{r}
fligner.test(
  pine ~ treatment,
  data = veg2)
```

```{r}
bartlett.test(pine ~ treatment, data = veg)
fligner.test(pine ~ treatment, data = veg)
```

```{r}
t.test(
  pine ~ treatment,
  data = veg2)
wilcox.test(
  pine ~ treatment,
  data = veg2)
```


```{r}
require(datarium)
data("mice2")
head(mice2)
```

```{r}
t.test(mice2$before, mice2$after, paired = TRUE)
```

```{r}
shapiro.test(mice2$before)
shapiro.test(mice2$after)
```

```{r}
wilcox.test(
  mice2$before, mice2$after,
  data = mice2, paired = TRUE)
```

```{r}
t.test(mice2$before, mice2$after, paired = FALSE)
```

```{r}
disp = read.csv(here("data", "dispersal.csv"))
disp
```
```{r}
plot(
  disp.rate.ftb ~ disp.rate.eb,
  data = disp,
  main = "Marbled Salamander Dispersal Rates",
  xlab = "Dispersal Rate\nFirst Time Breeders",
  ylab = "Dispersal Rate\nExperienced Breeders",
  pch = 21, col = 1, bg = "steelblue"
)
```

```{r}
cor.test(
  disp$disp.rate.ftb,
  disp$disp.rate.eb,
  use='complete.obs')
```

```{r}
cor.test(
  disp$disp.rate.ftb,
  disp$disp.rate.eb,
  use='complete.obs',
  method='spearman')
```

```{r}
plot(
  ecdf(disp$disp.rate.ftb),
  verticals=TRUE,
  main = "Mike's Plot of Marbled Salamanders\nFirst-Time Breeders: ECDF")
```

```{r}
cor.test(
  disp$disp.rate.ftb,
  disp$disp.rate.eb,
  use='complete.obs',
  method='spearman')
```

```{r}
plot(
  ecdf(disp$disp.rate.ftb),
  verticals=TRUE,
  main = "Mike's Plot of Marbled Salamanders\nFirst-Time Breeders: ECDF")
```

```{r}
plot(
  ecdf(disp$disp.rate.ftb),
  verticals=TRUE,
    main = "Mike's Plot of Marbled Salamanders\nFirst-Time and Experienced Breeders: ECDF")
plot(
  ecdf(disp$disp.rate.eb),
  verticals=TRUE,
  lty=3,
  add=TRUE)
legend(
  x = 0.4, y = 0.4,
  lty = c(1, 3),
  legend = c("first-time", "experienced"),
  title = "Breeder Class")
```

```{r}
ks.test(disp$disp.rate.ftb,disp$disp.rate.eb)
```

```{r}
prop.test(
  x = c(4,16),
  n = c(40,250))
```

```{r}
owls = matrix(c(16, 9, 4, 11), nrow=2)
rownames(owls) = c("present", "absent")
colnames(owls) = c("old", "young")
chisq_owls = chisq.test(owls)
chisq_owls
```

```{r}
round(chisq_owls$expected, 1)
chisq_owls$observed
round(
  chisq_owls$observed - chisq_owls$expected,
  digits = 1)
```

```{r}
fisher.test(owls)
```

##Question 1
##Making the contingency table
```{r}
birds   = read.csv(here("data", "bird.sta.csv"))
hab     = read.csv(here("data", "hab.sta.csv"))
birdhab = merge(
  birds,
  hab, by=c("basin", "sub", "sta"))

# Create a contingency table for edge/interior and brown creeper presence/absence
table(
  birdhab$s.edge,
  birdhab$BRCR > 0)

# set the presence to be in the first column
br_creeper_table = table(
  birdhab$s.edge, 
  birdhab$BRCR > 0)[, 2:1]

br_creeper_table
```

##Chi-Squared test of contingency table for brown creeprs
```{r}
chi_brcr = chisq.test(br_creeper_table)

round(chi_brcr$expected, 1)
chi_brcr$observed
round(
  chi_brcr$observed - chi_brcr$expected,
  digits = 1)
```

```{r}
require(palmerpenguins)
fit_fl_sp = 
  lm(
    formula = flipper_length_mm ~ species,
    data = penguins)

```

##Questions 3-5
```{r}
fit_species = 
  lm( 
    formula = body_mass_g ~ species,
    data = penguins)
fit_sex = 
  lm( 
    formula = body_mass_g ~ sex,
    data = penguins)
fit_both = 
  lm(
    formula = body_mass_g ~ (species * sex),
    data = penguins
  )
fit_both
```

```{r}
boxplot(body_mass_g ~ species, data = penguins, main = "Species Boxplot")
boxplot(body_mass_g ~ sex, data = penguins, main = "Sex Boxplot")
boxplot(body_mass_g ~ sex * species, xlab = NULL, data = penguins, main = "Doubly-Conditional Boxplot", las =2,
        names = c("Female\n Adelie", "Male\n Adelie", "Female\n Chinstrap", "Male\n Chinstrap", "Female\n Gentoo", "Male\n Gentoo") )
```

##Bartlett Tests
```{r}
bartlett.test(body_mass_g ~ species, data = penguins)
bartlett.test(body_mass_g ~ sex, data = penguins)
```

```{r}
dat_groups = aggregate(
  body_mass_g ~ sex * species,
  data = penguins,
  FUN = c)
str(dat_groups)

```
```{r}
bartlett.test(dat_groups$body_mass_g, data = dat_groups)
```
##Florida tree time
```{r}
require(here)
dat_fl = read.csv(here("data", "trees_Fl.csv"))
dat_fl
```
##Grouping data
```{r}
prob_fail = table(dat_fl$ProbabilityofFailure)
fail_stand = table(dat_fl$Failure_Standardized)
```


##Creating the four plots
```{r}
par(mfrow = c(2,2))
barplot(prob_fail)
barplot(fail_stand)
hist(dat_fl$DBH_in, main = "Histogram of DBH", xlab = "DBH (inches)")
plot(dat_fl$DBH_in, dat_fl$HeighttoTop_ft, main= "Scatterplot of DBH and Tree Height", xlab = "DBH (inches)", ylab = "Tree Height (feet)", cex = 0.2)

```

##KS tests
```{r}
dat_fl
dat_dbh = droplevels(subset(dat_fl, Failure_Standardized %in% c("whole", "none")))

dbh_whole = na.omit(subset(dat_dbh, Failure_Standardized == "whole"))
dbh_whole
dbh_none =  na.omit(subset(dat_dbh, Failure_Standardized == "none"))

ks.test(dbh_whole$DBH_in, dbh_none$DBH_in)
```

```{r}
dat_fl

cor.test(
  dat_fl$DBH_in, dat_fl$HeighttoTop_ft,
  method = "spearman"
)
```
```{r}
dat_fl$fail = factor(dat_fl$Failure_Standardized != "none")
levels(dat_fl$fail) = c("No Fail", "Fail")
fl_table_2 = table(
  dat_fl$ProbabilityofFailure,
  dat_fl$fail)
fl_table_2
chisq = chisq.test(fl_table_2)
round(chisq$observed - chisq$expected, digits = 1)

```

